### ISSUE TITLE
我在ubuntu 18.04上启动不了，一直在starting app....

### ISSUE THREAD

**Issue by bolunfeng** [kooritea/electronic-wechat#101]
#### Description

First of all, thanks for your attention to open an issue for this project.
Please notice that if you are requesting a **feature**, then you should give a **brief description** of your request.
If you are reporting a **bug**, please **follow the template** below.
A bug report **without detailed information** required will have a **very low priority** and even be **ignored** (closed directly)!

#### Specifications

- Version of Electron (run `$ electron --version`): `v0.0.0`
- OS: `<OS>`
- Stack trace from the error message (if any)

```
<Stack trace here>
```
> electronic-wechat@2.0.0 start /home/fengbolun/app/electronic-wechat
> electron src/main.js

WARNING: CommandOrControl + H is not a valid accelerator.

    at WeChatWindow.initWechatWindowShortcut (/home/fengbolun/app/electronic-wechat/src/windows/controllers/wechat.js:179:10)
    at new WeChatWindow (/home/fengbolun/app/electronic-wechat/src/windows/controllers/wechat.js:34:10)
    at ElectronicWeChat.createWeChatWindow (/home/fengbolun/app/electronic-wechat/src/main.js:136:25)
    at App.app.on (/home/fengbolun/app/electronic-wechat/src/main.js:50:12)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:191:7)

**Comment by kooritea** [comment]
看看系统设置网络那里是不是设置了代理？

**Comment by bolunfeng** [comment]
没有设置代理。就是一直在启动的时候，就是在starting App.....那里，不停的转。请问这是为什么呢？是什么情况可能导致这个情况的发生。以前有没有人反馈过这个情况？

**Comment by kooritea** [comment]
没注意你贴了报错信息- -

可能是ctrl+h热键被占用了？

**Comment by bolunfeng** [comment]
ctrl+h 这个热键被占用。我印象里应该没有特别的设置呀。只有我vim里的一两个插件有可能使用了ctrl+h的设置。这个应该不冲突吧？

**Comment by kooritea** [comment]
奇怪了  你用的是什么桌面？

**Comment by bolunfeng** [comment]
就是安装的ubuntu 18.04的啊

**Comment by kooritea** [comment]
https://github.com/kooritea/electronic-wechat/releases/tag/v2.3.1

试试fix版本？
