### ISSUE TITLE
v2.2.1启动失败

### ISSUE THREAD

**Issue by halk947** [kooritea/electronic-wechat#68]
#### Description

升级到最新版2.2.1后，无法启动

#### Specifications

- Version of Electron (run `$ electron --version`): `v2.2.1`
- OS: `Manjaro`
- Stack trace from the error message (if any)
App threw an error during load
TypeError: app.requestSingleInstanceLock is not a function
    at ElectronicWeChat.checkInstance (/usr/lib/electronic-wechat/src/main.js:38:16)
    at ElectronicWeChat.init (/usr/lib/electronic-wechat/src/main.js:26:13)
    at Object.<anonymous> (/usr/lib/electronic-wechat/src/main.js:214:24)
    at Object.<anonymous> (/usr/lib/electronic-wechat/src/main.js:216:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at loadApplicationPackage (/usr/lib/electron/resources/default_app.asar/main.js:287:12)
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: app.requestSingleInstanceLock is not a function
    at ElectronicWeChat.checkInstance (/usr/lib/electronic-wechat/src/main.js:38:16)
    at ElectronicWeChat.init (/usr/lib/electronic-wechat/src/main.js:26:13)
    at Object.<anonymous> (/usr/lib/electronic-wechat/src/main.js:214:24)
    at Object.<anonymous> (/usr/lib/electronic-wechat/src/main.js:216:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at loadApplicationPackage (/usr/lib/electron/resources/default_app.asar/main.js:287:12)

```
TypeError: app.requestSingleInstanceLock is not a function
```

**Comment by kooritea** [comment]
arch的electron好像是另外安装的？
这个问题是因为electron旧版本没有错误写到的那个方法
尝试更新electron？

**Comment by halk947** [comment]
> arch的electron好像是另外安装的？
> 这个问题是因为electron旧版本没有错误写到的那个方法
> 尝试更新electron？

查看本地的electron版本为`v2.0.12`，也是arch仓库里最新的版本

**Comment by kooritea** [comment]
我的锅
我把方法写死了，我还以为electron是一起打包进去的？

**Comment by kooritea** [comment]
在aur上看了一下
启动脚本
```bash
#!/bin/bash

PACKAGE_NAME="electronic-wechat"
EW_DIR="/usr/lib/$PACKAGE_NAME"

cd "$EW_DIR" || exit 1
exec /usr/bin/electron . "$@"
```

用的是全局安装的electron

其实直接用
```bash
/usr/lib/$PACKAGE_NAME/electron-wechat
```
就会使用内置的electron启动了

electron,npm,git,nodejs,python都不是运行依赖

当然如果 直接 ./electron-wechat 不能运行当我没说

**Comment by amitbha** [comment]
我是手动下载release，解压使用的，没用aur 😌

**Comment by summerIwinter** [comment]
在安装目录/usr/lib/electron-wechat里面
npm install electron --save-dev本地安装electron就可以了
