### ISSUE TITLE
Crash in KDE Desktop

### ISSUE THREAD

**Issue by sweeneycai** [kooritea/electronic-wechat#70]
#### Description

Crash in KDE Desktop.

#### Specifications

- Version of Electron (run `$ electron --version`): `Electron v2.0.12`
- OS: `Manjaro`

```
[sweeneycai@sweeneycai-pc ~]$ electronic-wechat 
App threw an error during load
TypeError: app.requestSingleInstanceLock is not a function
    at ElectronicWeChat.checkInstance (/usr/lib/electronic-wechat/src/main.js:38:16)
    at ElectronicWeChat.init (/usr/lib/electronic-wechat/src/main.js:26:13)
    at Object.<anonymous> (/usr/lib/electronic-wechat/src/main.js:214:24)
    at Object.<anonymous> (/usr/lib/electronic-wechat/src/main.js:216:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at loadApplicationPackage (/usr/lib/electron/resources/default_app.asar/main.js:287:12)
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: app.requestSingleInstanceLock is not a function
    at ElectronicWeChat.checkInstance (/usr/lib/electronic-wechat/src/main.js:38:16)
    at ElectronicWeChat.init (/usr/lib/electronic-wechat/src/main.js:26:13)
    at Object.<anonymous> (/usr/lib/electronic-wechat/src/main.js:214:24)
    at Object.<anonymous> (/usr/lib/electronic-wechat/src/main.js:216:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at loadApplicationPackage (/usr/lib/electron/resources/default_app.asar/main.js:287:12)
```

**Comment by kooritea** [comment]
aur 上面
https://aur.archlinux.org/packages/electronic-wechat/
这个包的启动脚本是有问题的，它使用的是独立安装的electron启动
独立安装的electron因为版本低没有requestSingleInstanceLock这个方法
#68 

这个https://aur.archlinux.org/packages/electronic-wechat-bin/是没问题的

**Comment by maoxuner** [comment]
最近感觉arch的包更新没那么快了，不知道是啥问题。
好多包都几个月没更新了。electron包已经1个月没更新了，现在还是v2
